name: Release

on:
    workflow_run:
        workflows: ["Build bump tag"]
        types:
            - completed
jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
                  scope: "@krokedil"
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
                  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
                  MY_GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
            - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GH_TOKEN}}"  >  ~/.npmrc
            - run: npm ci
            - run: npm publish
